### ISSUE TITLE
Find a more appropriate ways of dealing with several skewed values in Polity 5 dataset

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qStates#37]
There are several scores that read -66, -77 or -88 in across several variables in Polity 5. For different variables these values signal to different things. For now these values were all converted to NAs. However, we may want to find a better way of dealing with them as they are very numerous. There are information about what each of these mean on the codebook for data.

**Comment by BBieri** [comment]
## Quick description of the different codes from the codebook:
- **Interruption periods (-66):**
  - Polity is interrupted by an event and is reestablished after a time.
  - This happens when a country is occupied by foreign forces, when countries participate in short-lived attempts of ethnic, religious, or regional federations, or when foreign forces intervene in an interregnum period to help establish political order within the Polity.
- **Interregnum periods (-77)**
  - An interregnum is a period where the central political authority of a polity completely collapses. This happens during periods of internal wars as was the case in Lebanon from 1978 to 1986.
  - Three notes about this measure (see page 18 of the codebook for more details): 
    1. If the interregnal period results in the formation of a new polity, and it is less than a year,
the period is usually incorporated without separate mention in the "transition period" of the next
polity.
    2. If a country is occupied by foreign powers during wartime, terminating the old polity, then
reestablishes a polity after the foreign occupation ends, the intervening years are considered an
interregnum if a "new" polity is established; such cases are coded as an interruption (!66) on the
case variables and noted as an interregnum on the “state failure” (SF) variable, following.
    3. Interregnum periods are periods following a regime collapse but they do not necessarily equate to a regime transition e.g. if an authoritarian regime collapses, it does not necessarily end up being a democracy.
- **Transition Periods (-88)**
  - Transition periods occur when a regime change is planned executed and executed over time. During these events (and if they last more than a year), the polity is coded -88. 
  - Note that this code is only used if the change in either the composite DEMOC or AUTOC score is greater than +- 3. 
  - An example of this would be the interim government of Argentina in 1982 - 1983 after the fall of the junta. 

A final note about these codes. They are entered into the dataset in the year that the interregnum/interruption/transition period starts and takes precedence over existing polity scores and ends the year before the event is finished. Thus, if a civil war starts in December of 2021 in country X, the 2021 entry would be -77 to signal an interregnum period. Imagining that this war keeps on going until June 2023, the code for 2022 would still be -77 but revert to the "normal" polity score in 2023 of the following Polity.

**Comment by BBieri** [comment]
These are not skewed values per se @henriquesposito. They contain important information on the dynamic evolution of Polities as described above and should in my opinion be kept as such in the dataset to avoid confusing users with new codes. 

One thing I could do here is to create a vignette highlighting the most important aspects of this codebook to bring a bit more clarity into the interpretation of the values. What do you think?

**Comment by henriquesposito** [comment]
Thank you @BBieri for the clarifications. 

I do understand that these values represent coded categories, but they still might skew averages if present in columns alongside other values. In this sense, we might need to find better values to represent these or transform all to NA (as we are currently doing) if we want to use these columns for inferences, for example.    

@jhollway do you have an opinion about how to proceed here? Thank you.

**Comment by BBieri** [comment]
Thanks for your quick reply @henriquesposito ! How about transforming them to a character string then ? `-88` becomes `"Transition Period"`. That way, we have a "safety net" for naive users who don't read the codebook :)

**Comment by jhollway** [comment]
How would such a character string be able to be incorporated into an inferential workflow?

**Comment by BBieri** [comment]
## Progress note: 
`exrec`, `polcomp`, `prior`, `eprec`, `regtrans` variables are problematic in the sense that they contain true NA's. All other variables have been coded as missing (since they are complete ex ante) when the variables take one of the "skewed values". Additionally a new dummy variable called `speccat` has been created to acknowledge this extra layer of information.
